---
# tasks file for master
- name: Reset Kubernetes Master
  shell: kubeadm reset -f
  register: kubeadm_reset

- name: Generate token
  shell: kubeadm token generate
  register: token

- name: get token
  debug: var=token.stdout

- name: Initialize Master {{ kubernetes_version }}
  shell: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --token={{ token.stdout }} --pod-network-cidr={{ pod_network }} --token-ttl 0
  register: kubeadm_init
  when: kubeadm_reset is succeeded

- name: Create Kubernetes config directory
  file:
    path: /root/.kube/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy admin.conf to config directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: 0755
    remote_src: yes
    backup: yes
  when: kubeadm_init

- name: get join command
  shell: 'kubeadm token create --print-join-command | tee "/tmp/joincommand"'
  register: joincommand

- name: Fetch joincommand from master
  fetch: 
    src: "/tmp/joincommand" 
    dest: "joincommand.sh"
    flat: yes

- name: Install Flannel (Networking)
  shell: "curl -sSL https://rawgit.com/coreos/flannel/{{ flannel_version }}/Documentation/kube-flannel.yml | kubectl create -f -" 
  tags: flannel
  
# - name: Install CNI network with Weave
#   shell: "curl -sSL https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n') | kubectl create -f -" 
#   tags: weave

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_restart
