apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: web
  name: web
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - name: web
        image: docker.io/nokkie/app:1.0
        imagePullPolicy: Always
        readynessProbe:
          httpGet:
            path: /health
            port: http
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        command: ["/app"]
        ports:
        - name: http
          containerPort: 8080
      nodeSelector:
        name: node1

