apiVersion: v1
kind: Service
metadata:
  labels:
    run: web
  name: web
  namespace: production
spec:
  ports:
  - port: 8080
#    protocol: TCP
    targetPort: 8080
  selector:
    run: web
  type: NodePort
