apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: web2
  name: web2
  namespace: canary
spec:
  selector:
    matchLabels:
      run: web2
  template:
    metadata:
      labels:
        run: web2
    spec:
      containers:
      - name: web
        image: docker.io/nokkie/app:2.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: http
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        command: ["/app"]
        ports:
        - name: http
          containerPort: 8080

