apiVersion: v1
kind: Service
metadata:
  labels:
    run: web2
  name: web2
  namespace: canary
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: web2
  type: NodePort
