---
# tasks file for workers

- name: Copy joincommand to nodes
  copy: 
    src: "joincommand.sh" 
    dest: "/tmp/joincommand.sh"
    mode: '0755'
      
- name: execute join command
  shell: /tmp/joincommand.sh
  register: joinresults

- name: Show Join results
  debug: var=joinresults.stdout

#- name: Restart kubelet
#  systemd:
#    name: kubelet
#    state: restarted
#    daemon_reload: yes
#    enabled: yes
#  register: kubelet_restarted
