apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx2
  name: nginx2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - image: nginx:1
        name: nginx2
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: http
        volumeMounts:
        - name: custom-http
          mountPath: /usr/share/nginx/html/
      volumes:
        - name: custom-http
          configMap:
            name: custom-html
