---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
spec:
  ports:
  - name: http
    nodePort: 30203
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx2
  type: NodePort
