---
- name: Ensure hostname is in /boot/user_data
  replace:
    dest: /boot/user-data
    regexp: "^hostname: black-pearl"
    replace: "hostname: {{ ansible_hostname }}"
  register: hostname
  tags: hostname,userdata

- name: Set the nl locale
  lineinfile:
    path: /boot/user-data
    regexp: '^# locale'
    insertafter: '^# locale '
    line: 'locale: "nl_NL.UTF-8"'
  tags: locale,userdata

- name: Set the timezone
  lineinfile:
    path: /boot/user-data
    regexp: '^# timezone'
    insertafter: '^# timezone '
    line: 'timezone: "Europe/Amsterdam"'
  register: timezone
  tags: timezone,userdata  

- name: Disable wifi adapter
  lineinfile:
    path: /boot/config.txt
    insertafter: '^#dtoverlay=lirc-rpi'
    line: 'dtoverlay=pi3-disable-wifi'
  tags: wifi

- name: set rights on remote tmp directory
  file:
    path: /root/.ansible/tmp
    state: directory
    mode: 0755
  tags: staticip

- name: configure static IP
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
       # static IP configuration:
       interface eth0
       static ip_address={{ ansible_default_ipv4.address }}/24
       static routers={{ router_ip }}
       static domain_name_servers={{ dns_ip1 }} {{ dns_ip2 }}
  tags: staticip

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400
  tags: update

# - name: apt-get upgrade
#   apt:
#     upgrade: full
#   tags: upgrade

#- name: python-apt dependency
#  shell: apt-get install -y python-apt
#  args:
#    warn: no

- name: Reboot
  reboot:
  when: timezone or hostname is changed
  tags: reboot

