---
- name: Ensure hostname is in /boot/user_data
  replace:
    dest: /boot/user_data
    regexp: "^hostname: black-pearl"
    line: "hostname: {{ ansible_hostname }}"
  register: hostname
  tags: hostname

- name: set timezone to UTC
  timezone:
    name: Europe/Amsterdam
  register: timezone

- name: Disable wifi adapter
  lineinfile:
    path: /boot/config.txt
    insertafter: '^#dtoverlay=lirc-rpi'
    line: 'dtoverlay=pi3-disable-wifi'
  tags: wifi

- name: set rights on remote tmp directory
  file:
    path: /root/.ansible/tmp
    state: directory
    mode: 0755
  tags: staticip

- name: configure static IP
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
       # static IP configuration:
       interface eth0
       static ip_address={{ ansible_default_ipv4.address }}/24
       static routers={{ router_ip }}
       static domain_name_servers={{ dns_ip1 }} {{ dns_ip2 }}
  tags: staticip

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: apt-get upgrade
  apt:
    upgrade: full

- name: python-apt dependency
  shell: apt-get install -y python-apt
  args:
    warn: no

- name: Reboot
  reboot:
  #when: cmdline or timezone or hostname is changed
  when: timezone or cgroup or hostname is changed

