apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share
  namespace: default
spec:
  capacity:
    storage: 20Gi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.178.205
    path: /storage/testdata
